type Biomarker = {
  title: string;
  advanced?: boolean;
};

type BiomarkerCategory = {
  title: string;
  image: string;
  biomarkers: Biomarker[];
};

export const BIOMARKER_CATEGORIES: BiomarkerCategory[] = [
  {
    title: 'Longevity Markers',
    image: 'onboarding/biomarkers/longevity-markers.webp',
    biomarkers: [
      {
        title: 'Biological Age',
      },
      {
        title: 'Pace of Aging',
      },
      {
        title: 'Health Score',
      },
    ],
  },
  {
    title: 'Heart & Vascular Health',
    image: 'onboarding/biomarkers/heart-health.webp',
    biomarkers: [
      { title: 'Cholesterol, Total' },
      { title: 'HDL Cholesterol' },
      { title: 'Triglycerides' },
      { title: 'LDL-Cholesterol (calculated)' },
      { title: 'Cholesterol/HDL Ratio (calculated)' },
      { title: 'LDL/HDL Ratio (calculated)' },
      { title: 'Non-HDL Cholesterol (calculated)' },
      { title: 'Apolipoprotein B' },
      { title: 'LDL Cholesterol / Total Cholesterol (Mass Ratio)' },
      { title: 'Non-HDL Cholesterol / Total Cholesterol (Mass Ratio)' },
      { title: 'Triglyceride / HDL Cholesterol (Molar Ratio)' },
      { title: 'Atherogenic Index of Plasma (AIP)' },
      { title: 'Atherogenic Coefficient' },
      { title: 'Neutrophil-to-HDL Cholesterol Ratio (NHR)' },
      { title: 'TG / ApoB' },
      { title: 'LDL-C / ApoB' },
      { title: 'Non-HDL Cholesterol / Apolipoprotein B (Non-HDL-C / ApoB)' },
      { title: 'Uric Acid / HDL-C' },
      { title: 'Testosterone / ApoB' },
      { title: 'Lipoprotein (a)', advanced: true },
      { title: 'LDL P', advanced: true },
      { title: 'Small LDL P', advanced: true },
      { title: 'LDL Size', advanced: true },
      { title: 'HDL P', advanced: true },
      { title: 'Large HDL P', advanced: true },
      { title: 'HDL Size', advanced: true },
      { title: 'Large VLDL P', advanced: true },
      { title: 'VLDL Size', advanced: true },
    ],
  },
  {
    title: 'Metabolic Health',
    image: 'onboarding/biomarkers/metabolic-health.webp',
    biomarkers: [
      { title: 'Glucose' },
      { title: 'Hemoglobin A1C' },
      { title: 'Eag (Mg/Dl)' },
      { title: 'Eag (Mmol/L)' },
      { title: 'Uric Acid' },
      { title: '(Triglyceride - Glucose Index) - TyG Index' },
      { title: 'TyG-BMI Index' },
      { title: 'Corrected Calcium (Albumin-adjusted)' },
      { title: 'Estimated Glucose / HbA1c Ratio (Glycation Gap)' },
      { title: 'Insulin', advanced: true },
    ],
  },
  {
    title: 'Thyroid Health',
    image: 'onboarding/biomarkers/thyroid-health.webp',
    biomarkers: [
      { title: 'T3 Uptake' },
      { title: 'T4 (Thyroxine) Total' },
      { title: 'Free T4 Index (T7)' },
      { title: 'TSH' },
      { title: 'Thyroid Peroxidase Antibodies (TPO Ab)', advanced: true },
      { title: 'Thyroglobulin Antibodies (Tg Ab)', advanced: true },
      { title: 'Free T3', advanced: true },
    ],
  },
  {
    title: 'Sex Hormones',
    image: 'onboarding/biomarkers/sex-hormones.webp',
    biomarkers: [
      { title: 'Testosterone, Total, Males (Adult), Ia' },
      { title: 'Sex Hormone Binding Globulin' },
      { title: 'Testosterone, Free' },
      { title: 'Testosterone,Bioavailable' },
      { title: 'Estradiol' },
      { title: 'Free Androgen Index (FAI)' },
      { title: 'Testosterone / Estradiol (T:E2)' },
      { title: 'FSH (Follicle Stimulating Hormone)', advanced: true },
      { title: 'LH (Luteinizing Hormone)', advanced: true },
      { title: 'Progesterone', advanced: true },
      { title: 'Prolactin', advanced: true },
      { title: 'PSA, Free', advanced: true },
      { title: 'PSA, Total', advanced: true },
    ],
  },
  {
    title: 'Immune System',
    image: 'onboarding/biomarkers/immune-system.webp',
    biomarkers: [
      { title: 'White Blood Cell Count' },
      { title: 'Neutrophils' },
      { title: 'Absolute Neutrophils' },
      { title: 'Lymphocytes' },
      { title: 'Absolute Lymphocytes' },
      { title: 'Monocytes' },
      { title: 'Absolute Monocytes' },
      { title: 'Eosinophils' },
      { title: 'Absolute Eosinophils' },
      { title: 'Basophils' },
      { title: 'Absolute Basophils' },
      { title: 'Lymphocyte-to-Monocyte Ratio (LMR)' },
      { title: 'Neutrophil-to-Lymphocyte Ratio' },
      { title: 'Platelet-to-WBC Ratio' },
      { title: 'Neutrophil-to-Lymphocyte & Platelet Ratio (NLPR)' },
      { title: 'Monocyte-to-Lymphocyte Ratio (MLR)' },
    ],
  },
  {
    title: 'Inflammation',
    image: 'onboarding/biomarkers/inflammation.webp',
    biomarkers: [
      { title: 'hs-CRP' },
      { title: 'Systemic Immune-Inflammation Index (SII)' },
      { title: 'Monocyte-to-HDL Ratio (MHR)' },
      { title: 'Platelet-to-Lymphocyte Ratio' },
      { title: 'Systemic Inflammation Response Index (SIRI)' },
      { title: 'Ferritin-to-Albumin Ratio (FAR)' },
      { title: 'CRP / Albumin Ratio (CAR)' },
      { title: 'CRP-to-Lymphocyte Ratio' },
      { title: 'CRP / DHEA-S Ratio' },
      { title: 'Testosterone / CRP' },
      { title: 'Sed Rate by Modified Westergren', advanced: true },
    ],
  },
  {
    title: 'Kidney Health',
    image: 'onboarding/biomarkers/kidney-health.webp',
    biomarkers: [
      { title: 'BUN/Creatinine Ratio (calculated)' },
      { title: 'Calcium' },
      { title: 'Carbon Dioxide' },
      { title: 'Chloride' },
      { title: 'Creatinine' },
      { title: 'eGFR' },
      { title: 'Potassium' },
      { title: 'Sodium' },
      { title: 'Urea Nitrogen' },
      { title: 'Cockcroft-Gault Creatinine Clearance' },
    ],
  },
  {
    title: 'Liver Health',
    image: 'onboarding/biomarkers/liver-health.webp',
    biomarkers: [
      { title: 'Albumin' },
      { title: 'Albumin/Globulin Ratio (calculated)' },
      { title: 'Alkaline Phosphatase' },
      { title: 'ALT' },
      { title: 'AST' },
      { title: 'Globulin (calculated)' },
      { title: 'Total Bilirubin' },
      { title: 'Bilirubin, Direct' },
      { title: 'Bilirubin, Indirect' },
      { title: 'Gamma Glutamyl Transferase (GGT)' },
      { title: 'De Ritis (AST / ALT) Ratio' },
      { title: 'Indirect-to-Direct Bilirubin Ratio (I/D Bilirubin Ratio)' },
      { title: 'Bilirubin-to-Albumin Ratio (BAR)' },
      { title: 'GGT-to-HDL Cholesterol Ratio (GGT / HDL-C)' },
      { title: 'GGT / ALT' },
    ],
  },
  {
    title: 'Nutrients',
    image: 'onboarding/biomarkers/nutrients.webp',
    biomarkers: [
      { title: 'Red Blood Cell Count' },
      { title: 'Hemoglobin' },
      { title: 'Hematocrit' },
      { title: 'Mcv' },
      { title: 'Mch' },
      { title: 'Mchc' },
      { title: 'Rdw' },
      { title: 'Platelet Count' },
      { title: 'Mpv' },
      { title: 'Total Protein' },
      { title: 'Vitamin D, 25-Hydroxy, Total' },
      { title: 'RDW / MCV Ratio' },
    ],
  },
  {
    title: 'Energy',
    image: 'onboarding/biomarkers/energy.webp',
    biomarkers: [
      { title: 'Total Iron' },
      { title: 'Iron Binding Capacity' },
      { title: '% Saturation (calculated)' },
      { title: 'Ferritin' },
      { title: 'Cortisol, Total' },
      { title: 'RDW / Ferritin Ratio' },
      { title: 'Cortisol-to-DHEA-S Ratio' },
    ],
  },
  {
    title: 'DNA Health',
    image: 'onboarding/biomarkers/dna-health.webp',
    biomarkers: [
      { title: 'Homocysteine', advanced: true },
      { title: 'Vitamin B12 (Cobalamin)', advanced: true },
      { title: 'Folate', advanced: true },
    ],
  },
  {
    title: 'Body Composition',
    image: 'onboarding/biomarkers/body-composition.webp',
    biomarkers: [{ title: 'IGF-1', advanced: true }],
  },
];
