apiVersion: skaffold/v3
kind: Config
metadata:
  name: react-app
build:
  platforms: ["linux/arm64"]
  artifacts:
    - image: react-app
      context: ../../
      docker:
        dockerfile: deployment/dev/Dockerfile
      sync:
        infer:
          - "**/*"
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: false
manifests:
  kustomize:
    paths:
      - kustomization/app
    buildArgs: ["--enable-alpha-plugins", "--enable-exec"]
deploy:
  kubectl:
    defaultNamespace: superpower
portForward:
  - resourceType: deployment
    resourceName: react-app
    namespace: superpower
    port: 3000
    localPort: 3000