apiVersion: v1
kind: Namespace
metadata:
  name: superpower
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: superpower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: react-app:latest
          # imagePullPolicy: Always # or IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: VITE_APP_API_URL
              value: '{{ .VITE_APP_API_URL }}'
            - name: VITE_APP_ENABLE_API_MOCKING
              value: '{{ .VITE_APP_ENABLE_API_MOCKING }}'
            - name: VITE_APP_STRIPE_PUBLISHABLE_KEY
              value: '{{ .VITE_APP_STRIPE_PUBLISHABLE_KEY }}'
            - name: VITE_APP_VITAL_ENV
              value: '{{ .VITE_APP_VITAL_ENV }}'
            - name: VITE_APP_GOOGLE_API_KEY
              value: '{{ .VITE_APP_GOOGLE_API_KEY }}'
            - name: VITE_APP_CALENDLY_TOKEN
              value: '{{ .VITE_APP_CALENDLY_TOKEN }}'
            - name: VITE_APP_TYPEFORM_FORM_ID
              value: '{{ .VITE_APP_TYPEFORM_FORM_ID }}'
            - name: VITE_APP_BRIDGE_PUBLISHABLE_KEY
              value: '{{ .VITE_APP_BRIDGE_PUBLISHABLE_KEY }}'
            - name: VITE_APP_BRIDGE_ENDPOINT
              value: '{{ .VITE_APP_BRIDGE_ENDPOINT }}'
            - name: VITE_APP_KLAVIYO_LIST_ID
              value: '{{ .VITE_APP_KLAVIYO_LIST_ID }}'
            - name: VITE_APP_KLAVIYO_PUBLIC_API_KEY
              value: '{{ .VITE_APP_KLAVIYO_PUBLIC_API_KEY }}'
            - name: VITE_APP_GO_RX_URL
              value: '{{ .VITE_APP_GO_RX_URL }}'

---
apiVersion: v1
kind: Service
metadata:
  name: react-app
  namespace: superpower
spec:
  type: LoadBalancer # Changed from LoadBalancer to NodePort
  selector:
    app: react-app
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
