// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type User = Entity<{
  firstName: string;
  lastName: string;
  email: string;
  role: 'ADMIN' | 'USER';
  bio: string;
}>;

export type AuthResponse = {
  jwt: string;
  user: User;
};

export type ServiceabilityResponse = {
  serviceable: boolean;
};

export type Questionnaire = Entity<{
  id: string;
}>;

export type Address = Entity<{
  line: string[];
  city: string;
  state: string;
  postalCode: string;
}>;

export type HealthcareService = Entity<{
  id: string;
  name: string;
  description: string;
  image: string;
  price: number;
  items: [];
}>;

export type Order = Entity<{
  id: string;
}>;

export type Biomarker = Entity<{
  id: string;
}>;

export type Consult = Entity<{
  id: string;
  name: string;
  practitioner: string;
}>;

export type Message = Entity<{
  body: string;
}>;

export type VerifyOPT = {
  success: boolean;
};

export type Slot = {
  start: string;
  end: string;
};

export type Price = {
  total: number;
  // items
};

export type CollectionMethodType = 'AT_HOME' | 'IN_LAB' | 'PHLEBOTOMY_KIT';
