/*
This ordering is based on https://www.notion.so/Results-database-ordering-a8b2c493b4164695a920dcfe2d98c6eb
but contains all items from the ObservationDefinition airtable as of 2024-04-19
*/

import { Biomarker } from '@/types/api';

export const orderBiomarkerCards = (biomarkers: Biomarker[]): Biomarker[] => {
  const orderOfNames: string[] = [
    'Biological Age',
    'Pace of Aging',
    'Cholesterol, Total', // Cardiometabolic,
    'LDL Cholesterol', // Cardiometabolic,
    'VLDL Cholesterol', // Cardiometabolic,
    'HDL Cholesterol', // Cardiometabolic,
    'Triglycerides', // Cardiometabolic,
    'Apolipoprotein B', // Cardiometabolic,
    'Lipoprotein (a)', // Cardiometabolic,
    'Glucose', // Cardiometabolic,
    'Hemoglobin A1c', // Cardiometabolic,
    'Insulin', // Cardiometabolic,
    'Homocysteine', // Cardiometabolic,
    // end sorted cardiometabolic
    'Apo E Genotyping: Cardio Risk', // Cardiometabolic,
    'HDL Particle Percentile', // Cardiometabolic,
    'HDL Size Percentile', // Cardiometabolic,
    'HDL-P', // Cardiometabolic,
    'IGF-1', // Cardiometabolic,
    'Insulin Resistance Score', // Cardiometabolic,
    'Iodine, Serum or Plasma', // Cardiometabolic,
    'Large HDL Particle Percentile', // Cardiometabolic,
    'Large VLDL Particle Percentile', // Cardiometabolic,
    'LDL and HDL Particles', // Cardiometabolic,
    'LDL Particle Number', // Cardiometabolic,
    'LDL Size', // Cardiometabolic,
    'LDL Size Percentile', // Cardiometabolic,
    'LDL-P', // Cardiometabolic,
    'LDL/HDL Ratio', // Cardiometabolic,
    'LP-IR Score', // Cardiometabolic,
    'LP-IR Score Percentile', // Cardiometabolic,
    'NMR Fractions-Std.', // Cardiometabolic,
    'Non-HDL Cholesterol', // Cardiometabolic,
    'Small LDL Particle Percentile', // Cardiometabolic,
    'Small LDL-P', // Cardiometabolic,
    'VLDL Size Percentile', // Cardiometabolic,

    'Omega-6 total', // Nutrition and Inflammation,
    'Linoleic Acid', // Nutrition and Inflammation,
    'Arachidonic Acid', // Nutrition and Inflammation,
    'Omega-3 total', // Nutrition and Inflammation,
    'DHA', // Nutrition and Inflammation,
    'DPA', // Nutrition and Inflammation,
    'EPA', // Nutrition and Inflammation,
    'Omega-6/Omega-3 Ratio', // Nutrition and Inflammation,
    'Arachidonic Acid/EPA Ratio', // Nutrition and Inflammation,
    'Vitamin B12', // Nutrition and Inflammation,
    'Vitamin D', // Nutrition and Inflammation,
    'Magnesium', // Nutrition and Inflammation,
    'Zinc', // Nutrition and Inflammation,
    'C-Reactive Protein (CRP)', // Nutrition and Inflammation,
    // end sorted Nutrition and Inflammation
    'Antinuclear Antibodies (ANA)', // Nutrition and Inflammation,
    'Centriole Pattern', // Nutrition and Inflammation,
    'Centromere Pattern', // Nutrition and Inflammation,
    'ESR (Sedimentation Rate, Modified Westergren)', // Nutrition and Inflammation,
    'Folate (Folic Acid), Serum', // Nutrition and Inflammation,
    'Nuclear Dot Pattern', // Nutrition and Inflammation,
    'Nuclear Membrane Pattern', // Nutrition and Inflammation,
    'Nucleolar Pattern', // Nutrition and Inflammation,
    'PCNA Pattern', // Nutrition and Inflammation,
    'Pffa', // Nutrition and Inflammation,
    'Prot and Pffa Calc', // Nutrition and Inflammation,
    'Rheumatoid Arthritis Factor (RF)', // Nutrition and Inflammation,
    'Selenium, Blood', // Nutrition and Inflammation,
    'Selenium, Serum/Plasma', // Nutrition and Inflammation,
    'Speckled Pattern', // Nutrition and Inflammation,
    'Spindle Apparatus Pattern', // Nutrition and Inflammation,
    'Vitamin A, Serum', // Nutrition and Inflammation,

    'Red Blood Cells', // Blood and Oxygen,
    'NRBC', // Blood and Oxygen,
    'White Blood Cells', // Blood and Oxygen,
    'Hemoglobin', // Blood and Oxygen,
    'Hematocrit', // Blood and Oxygen,
    'Platelet Count', // Blood and Oxygen,
    'Mean Cell Volume (MCV)', // Blood and Oxygen,
    'Mean Cell Hemoglobin (MCH)', // Blood and Oxygen,
    'Mean Corpuscular Hemoglobin Concentration (MCHC)', // Blood and Oxygen,
    'Red Cell Dist Width (RDW)', // Blood and Oxygen,
    'Lymphocytes', // Blood and Oxygen,
    'Lymphs (Absolute)', // Blood and Oxygen,
    'Eosinophils', // Blood and Oxygen,
    'Eos (Absolute)', // Blood and Oxygen,
    'Basophils', // Blood and Oxygen,
    'Baso (Absolute)', // Blood and Oxygen,
    'Immature Cells', // Blood and Oxygen,
    'Immature Granulocytes', // Blood and Oxygen,
    'Immature Grans (Abs)', // Blood and Oxygen,
    'Monocytes', // Blood and Oxygen,
    'Monocytes (Absolute)', // Blood and Oxygen,
    'Neutrophils', // Blood and Oxygen,
    'Neutrophils (Absolute)', // Blood and Oxygen,
    'Neut/Lymph Ratio', // Blood and Oxygen,
    'Iron', // Blood and Oxygen,
    'Iron Saturation', // Blood and Oxygen,
    'Total Iron Binding Capacity (TIBC)', // Blood and Oxygen,
    'Unsaturated Iron-Binding Capacity (UIBC)', // Blood and Oxygen,
    'Ferritin', // Blood and Oxygen,

    'Aspartate Aminotransferase (AST)', // Liver and Kidney Health,
    'Alanine Aminotransferase (ALT)', // Liver and Kidney Health,
    'Alkaline Phosphatase (ALP)', // Liver and Kidney Health,
    'Bilirubin, Total', // Liver and Kidney Health,
    'Protein', // Liver and Kidney Health,
    'Protein, Total', // Liver and Kidney Health,
    'Albumin', // Liver and Kidney Health,
    'Globulin, Total', // Liver and Kidney Health,
    'Globulin A/G Ratio', // Liver and Kidney Health,
    'Blood Urea Nitrogen (BUN)', // Liver and Kidney Health,
    'Creatinine', // Liver and Kidney Health,
    'BUN/Creatinine Ratio', // Liver and Kidney Health,
    'Estimated Glomerular Filtration Rate (eGFR)', // Liver and Kidney Health,
    'Sodium', // Liver and Kidney Health,
    'Potassium', // Liver and Kidney Health,
    'Chloride', // Liver and Kidney Health,
    'Carbon Dioxide, Total', // Liver and Kidney Health,
    'Calcium', // Liver and Kidney Health,
    'Uric Acid', // Liver and Kidney Health,

    'Thyroid-Stimulating Hormone (TSH)', // Hormones,
    'Thyroglobulin Antibodies (TgAb)', // Hormones,
    'Thyroid Peroxidase (TPO)', // Hormones,
    'Thyroxine (Free T4)', // Hormones,
    'Triiodothyronine (T3)', // Hormones,
    'Testosterone, Total', // Hormones,
    'Free Testosterone', // Hormones,
    'Estradiol', // Hormones,
    'Sex Hormone Binding Globulin (SHBG)', // Hormones,
    'Progesterone', // Hormones,
    'Prolactin', // Hormones,
    'Follicle Stimulating Hormone (FSH)', // Hormones,
    'Luteinizing hormone (LH)', // Hormones,
    'DHEA-Sulfate (DHEA-S)', // Hormones,
    'Cortisol', // Hormones,
    // end sorted Hormones
    'Anti-Mullerian Hormone (AMH)', // Hormones,
    'DHT, Free', // Hormones,
    'DHT, Percent Free Dialysis', // Hormones,
    'Dihydrotestosterone (DHT)', // Hormones,
    'Estradiol, Sensitive', // Hormones,
    'Procalcitonin', // Hormones,
    'Progesterone, Serum', // Hormones,
    'Prostate Specific Antigen (PSA)', // Hormones,
    'PSA, Complexed', // Hormones,
    'Lead', // Toxins,
    'Mercury', // Toxins
  ];

  const customSort = (a: Biomarker, b: Biomarker): number => {
    const indexOfA = orderOfNames.indexOf(a.name);
    const indexOfB = orderOfNames.indexOf(b.name);

    return indexOfA === -1 || indexOfB === -1
      ? indexOfB - indexOfA
      : indexOfA - indexOfB;
  };

  return [...biomarkers].sort(customSort);
};
