export const CHART_CONFIG = {
  SVG_HEIGHT: 300,
  LEFT_PADDING: 36,
  RIGHT_PADDING: 40,
  TOP_PADDING: 32,
  BOTTOM_PADDING: 48,
  DATA_INSET: 12,
  STROKE_WIDTH: 2,
  LINE_COLOR: '#a1a1aa',
  HOVER_LINE_COLOR: '#d4d4d8',
  BASELINE_COLOR: '#d4d4d8',
  Y_TICK_COUNT: 5,
} as const;
