/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetpasswordRouteImport } from './routes/resetpassword'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ClaimBenefitRouteImport } from './routes/claim-benefit'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVaultRouteImport } from './routes/_app.vault'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppProtocolRouteImport } from './routes/_app.protocol'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppMarketplaceRouteImport } from './routes/_app.marketplace'
import { Route as AppInviteRouteImport } from './routes/_app.invite'
import { Route as AppIntakeRouteImport } from './routes/_app.intake'
import { Route as AppFamilyRiskRouteImport } from './routes/_app.family-risk'
import { Route as AppDataRouteImport } from './routes/_app.data'
import { Route as AppConciergeRouteImport } from './routes/_app.concierge'
import { Route as AppMapsRouteImport } from './routes/_app._maps'
import { Route as AppServicesIndexRouteImport } from './routes/_app.services.index'
import { Route as AppProtocolIndexRouteImport } from './routes/_app.protocol.index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app.orders.index'
import { Route as AppDataIndexRouteImport } from './routes/_app.data.index'
import { Route as AppConciergeIndexRouteImport } from './routes/_app.concierge.index'
import { Route as SetpasswordIdSecretRouteImport } from './routes/setpassword.$id.$secret'
import { Route as AppServicesIdRouteImport } from './routes/_app.services.$id'
import { Route as AppQuestionnaireTypeRouteImport } from './routes/_app.questionnaire.$type'
import { Route as AppProtocolRevealRouteImport } from './routes/_app.protocol.reveal'
import { Route as AppProtocolPlansRouteImport } from './routes/_app.protocol.plans'
import { Route as AppProtocolAutopilotRouteImport } from './routes/_app.protocol.autopilot'
import { Route as AppPrescriptionsIdRouteImport } from './routes/_app.prescriptions.$id'
import { Route as AppPlansIdRouteImport } from './routes/_app.plans.$id'
import { Route as AppOrdersIdRouteImport } from './routes/_app.orders.$id'
import { Route as AppFamilyRiskPlanRouteImport } from './routes/_app.family-risk.plan'
import { Route as AppDataRecordsRouteImport } from './routes/_app.data.records'
import { Route as AppConciergeIdRouteImport } from './routes/_app.concierge.$id'
import { Route as AppMapsUsersRouteImport } from './routes/_app._maps.users'
import { Route as AppMapsSettingsRouteImport } from './routes/_app._maps.settings'
import { Route as AppMapsScheduleRouteImport } from './routes/_app._maps.schedule'
import { Route as AppMapsOnboardingRouteImport } from './routes/_app._maps.onboarding'
import { Route as AppProtocolRevealIndexRouteImport } from './routes/_app.protocol.reveal.index'
import { Route as AppProtocolRevealStepRouteImport } from './routes/_app.protocol.reveal.$step'
import { Route as AppProtocolPlansIdRouteImport } from './routes/_app.protocol.plans.$id'
import { Route as AppProtocolPlansPlanIdGoalsGoalIdRouteImport } from './routes/_app.protocol.plans.$planId.goals.$goalId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetpasswordRoute = ResetpasswordRouteImport.update({
  id: '/resetpassword',
  path: '/resetpassword',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimBenefitRoute = ClaimBenefitRouteImport.update({
  id: '/claim-benefit',
  path: '/claim-benefit',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppProtocolRoute = AppProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteRoute = AppInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AppRoute,
} as any)
const AppIntakeRoute = AppIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyRiskRoute = AppFamilyRiskRouteImport.update({
  id: '/family-risk',
  path: '/family-risk',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRoute,
} as any)
const AppConciergeRoute = AppConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => AppRoute,
} as any)
const AppMapsRoute = AppMapsRouteImport.update({
  id: '/_maps',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppServicesRoute,
} as any)
const AppProtocolIndexRoute = AppProtocolIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProtocolRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppDataIndexRoute = AppDataIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDataRoute,
} as any)
const AppConciergeIndexRoute = AppConciergeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConciergeRoute,
} as any)
const SetpasswordIdSecretRoute = SetpasswordIdSecretRouteImport.update({
  id: '/setpassword/$id/$secret',
  path: '/setpassword/$id/$secret',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServicesIdRoute = AppServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppServicesRoute,
} as any)
const AppQuestionnaireTypeRoute = AppQuestionnaireTypeRouteImport.update({
  id: '/questionnaire/$type',
  path: '/questionnaire/$type',
  getParentRoute: () => AppRoute,
} as any)
const AppProtocolRevealRoute = AppProtocolRevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => AppProtocolRoute,
} as any)
const AppProtocolPlansRoute = AppProtocolPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppProtocolRoute,
} as any)
const AppProtocolAutopilotRoute = AppProtocolAutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => AppProtocolRoute,
} as any)
const AppPrescriptionsIdRoute = AppPrescriptionsIdRouteImport.update({
  id: '/prescriptions/$id',
  path: '/prescriptions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansIdRoute = AppPlansIdRouteImport.update({
  id: '/plans/$id',
  path: '/plans/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppFamilyRiskPlanRoute = AppFamilyRiskPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppFamilyRiskRoute,
} as any)
const AppDataRecordsRoute = AppDataRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppDataRoute,
} as any)
const AppConciergeIdRoute = AppConciergeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppConciergeRoute,
} as any)
const AppMapsUsersRoute = AppMapsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppMapsRoute,
} as any)
const AppMapsSettingsRoute = AppMapsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppMapsRoute,
} as any)
const AppMapsScheduleRoute = AppMapsScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppMapsRoute,
} as any)
const AppMapsOnboardingRoute = AppMapsOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppMapsRoute,
} as any)
const AppProtocolRevealIndexRoute = AppProtocolRevealIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProtocolRevealRoute,
} as any)
const AppProtocolRevealStepRoute = AppProtocolRevealStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => AppProtocolRevealRoute,
} as any)
const AppProtocolPlansIdRoute = AppProtocolPlansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProtocolPlansRoute,
} as any)
const AppProtocolPlansPlanIdGoalsGoalIdRoute =
  AppProtocolPlansPlanIdGoalsGoalIdRouteImport.update({
    id: '/$planId/goals/$goalId',
    path: '/$planId/goals/$goalId',
    getParentRoute: () => AppProtocolPlansRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/check-email': typeof CheckEmailRoute
  '/claim-benefit': typeof ClaimBenefitRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/resetpassword': typeof ResetpasswordRoute
  '/signin': typeof SigninRoute
  '/verify-email': typeof VerifyEmailRoute
  '/concierge': typeof AppConciergeRouteWithChildren
  '/data': typeof AppDataRouteWithChildren
  '/family-risk': typeof AppFamilyRiskRouteWithChildren
  '/intake': typeof AppIntakeRoute
  '/invite': typeof AppInviteRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/orders': typeof AppOrdersRouteWithChildren
  '/protocol': typeof AppProtocolRouteWithChildren
  '/services': typeof AppServicesRouteWithChildren
  '/vault': typeof AppVaultRoute
  '/onboarding': typeof AppMapsOnboardingRoute
  '/schedule': typeof AppMapsScheduleRoute
  '/settings': typeof AppMapsSettingsRoute
  '/users': typeof AppMapsUsersRoute
  '/concierge/$id': typeof AppConciergeIdRoute
  '/data/records': typeof AppDataRecordsRoute
  '/family-risk/plan': typeof AppFamilyRiskPlanRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/plans/$id': typeof AppPlansIdRoute
  '/prescriptions/$id': typeof AppPrescriptionsIdRoute
  '/protocol/autopilot': typeof AppProtocolAutopilotRoute
  '/protocol/plans': typeof AppProtocolPlansRouteWithChildren
  '/protocol/reveal': typeof AppProtocolRevealRouteWithChildren
  '/questionnaire/$type': typeof AppQuestionnaireTypeRoute
  '/services/$id': typeof AppServicesIdRoute
  '/setpassword/$id/$secret': typeof SetpasswordIdSecretRoute
  '/concierge/': typeof AppConciergeIndexRoute
  '/data/': typeof AppDataIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/protocol/': typeof AppProtocolIndexRoute
  '/services/': typeof AppServicesIndexRoute
  '/protocol/plans/$id': typeof AppProtocolPlansIdRoute
  '/protocol/reveal/$step': typeof AppProtocolRevealStepRoute
  '/protocol/reveal/': typeof AppProtocolRevealIndexRoute
  '/protocol/plans/$planId/goals/$goalId': typeof AppProtocolPlansPlanIdGoalsGoalIdRoute
}
export interface FileRoutesByTo {
  '/check-email': typeof CheckEmailRoute
  '/claim-benefit': typeof ClaimBenefitRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/resetpassword': typeof ResetpasswordRoute
  '/signin': typeof SigninRoute
  '/verify-email': typeof VerifyEmailRoute
  '/': typeof AppIndexRoute
  '/family-risk': typeof AppFamilyRiskRouteWithChildren
  '/intake': typeof AppIntakeRoute
  '/invite': typeof AppInviteRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/vault': typeof AppVaultRoute
  '/onboarding': typeof AppMapsOnboardingRoute
  '/schedule': typeof AppMapsScheduleRoute
  '/settings': typeof AppMapsSettingsRoute
  '/users': typeof AppMapsUsersRoute
  '/concierge/$id': typeof AppConciergeIdRoute
  '/data/records': typeof AppDataRecordsRoute
  '/family-risk/plan': typeof AppFamilyRiskPlanRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/plans/$id': typeof AppPlansIdRoute
  '/prescriptions/$id': typeof AppPrescriptionsIdRoute
  '/protocol/autopilot': typeof AppProtocolAutopilotRoute
  '/protocol/plans': typeof AppProtocolPlansRouteWithChildren
  '/questionnaire/$type': typeof AppQuestionnaireTypeRoute
  '/services/$id': typeof AppServicesIdRoute
  '/setpassword/$id/$secret': typeof SetpasswordIdSecretRoute
  '/concierge': typeof AppConciergeIndexRoute
  '/data': typeof AppDataIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/protocol': typeof AppProtocolIndexRoute
  '/services': typeof AppServicesIndexRoute
  '/protocol/plans/$id': typeof AppProtocolPlansIdRoute
  '/protocol/reveal/$step': typeof AppProtocolRevealStepRoute
  '/protocol/reveal': typeof AppProtocolRevealIndexRoute
  '/protocol/plans/$planId/goals/$goalId': typeof AppProtocolPlansPlanIdGoalsGoalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/claim-benefit': typeof ClaimBenefitRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/resetpassword': typeof ResetpasswordRoute
  '/signin': typeof SigninRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/_maps': typeof AppMapsRouteWithChildren
  '/_app/concierge': typeof AppConciergeRouteWithChildren
  '/_app/data': typeof AppDataRouteWithChildren
  '/_app/family-risk': typeof AppFamilyRiskRouteWithChildren
  '/_app/intake': typeof AppIntakeRoute
  '/_app/invite': typeof AppInviteRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/orders': typeof AppOrdersRouteWithChildren
  '/_app/protocol': typeof AppProtocolRouteWithChildren
  '/_app/services': typeof AppServicesRouteWithChildren
  '/_app/vault': typeof AppVaultRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_maps/onboarding': typeof AppMapsOnboardingRoute
  '/_app/_maps/schedule': typeof AppMapsScheduleRoute
  '/_app/_maps/settings': typeof AppMapsSettingsRoute
  '/_app/_maps/users': typeof AppMapsUsersRoute
  '/_app/concierge/$id': typeof AppConciergeIdRoute
  '/_app/data/records': typeof AppDataRecordsRoute
  '/_app/family-risk/plan': typeof AppFamilyRiskPlanRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
  '/_app/plans/$id': typeof AppPlansIdRoute
  '/_app/prescriptions/$id': typeof AppPrescriptionsIdRoute
  '/_app/protocol/autopilot': typeof AppProtocolAutopilotRoute
  '/_app/protocol/plans': typeof AppProtocolPlansRouteWithChildren
  '/_app/protocol/reveal': typeof AppProtocolRevealRouteWithChildren
  '/_app/questionnaire/$type': typeof AppQuestionnaireTypeRoute
  '/_app/services/$id': typeof AppServicesIdRoute
  '/setpassword/$id/$secret': typeof SetpasswordIdSecretRoute
  '/_app/concierge/': typeof AppConciergeIndexRoute
  '/_app/data/': typeof AppDataIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/protocol/': typeof AppProtocolIndexRoute
  '/_app/services/': typeof AppServicesIndexRoute
  '/_app/protocol/plans/$id': typeof AppProtocolPlansIdRoute
  '/_app/protocol/reveal/$step': typeof AppProtocolRevealStepRoute
  '/_app/protocol/reveal/': typeof AppProtocolRevealIndexRoute
  '/_app/protocol/plans/$planId/goals/$goalId': typeof AppProtocolPlansPlanIdGoalsGoalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-email'
    | '/claim-benefit'
    | '/logout'
    | '/register'
    | '/resetpassword'
    | '/signin'
    | '/verify-email'
    | '/concierge'
    | '/data'
    | '/family-risk'
    | '/intake'
    | '/invite'
    | '/marketplace'
    | '/orders'
    | '/protocol'
    | '/services'
    | '/vault'
    | '/onboarding'
    | '/schedule'
    | '/settings'
    | '/users'
    | '/concierge/$id'
    | '/data/records'
    | '/family-risk/plan'
    | '/orders/$id'
    | '/plans/$id'
    | '/prescriptions/$id'
    | '/protocol/autopilot'
    | '/protocol/plans'
    | '/protocol/reveal'
    | '/questionnaire/$type'
    | '/services/$id'
    | '/setpassword/$id/$secret'
    | '/concierge/'
    | '/data/'
    | '/orders/'
    | '/protocol/'
    | '/services/'
    | '/protocol/plans/$id'
    | '/protocol/reveal/$step'
    | '/protocol/reveal/'
    | '/protocol/plans/$planId/goals/$goalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/check-email'
    | '/claim-benefit'
    | '/logout'
    | '/register'
    | '/resetpassword'
    | '/signin'
    | '/verify-email'
    | '/'
    | '/family-risk'
    | '/intake'
    | '/invite'
    | '/marketplace'
    | '/vault'
    | '/onboarding'
    | '/schedule'
    | '/settings'
    | '/users'
    | '/concierge/$id'
    | '/data/records'
    | '/family-risk/plan'
    | '/orders/$id'
    | '/plans/$id'
    | '/prescriptions/$id'
    | '/protocol/autopilot'
    | '/protocol/plans'
    | '/questionnaire/$type'
    | '/services/$id'
    | '/setpassword/$id/$secret'
    | '/concierge'
    | '/data'
    | '/orders'
    | '/protocol'
    | '/services'
    | '/protocol/plans/$id'
    | '/protocol/reveal/$step'
    | '/protocol/reveal'
    | '/protocol/plans/$planId/goals/$goalId'
  id:
    | '__root__'
    | '/_app'
    | '/check-email'
    | '/claim-benefit'
    | '/logout'
    | '/register'
    | '/resetpassword'
    | '/signin'
    | '/verify-email'
    | '/_app/_maps'
    | '/_app/concierge'
    | '/_app/data'
    | '/_app/family-risk'
    | '/_app/intake'
    | '/_app/invite'
    | '/_app/marketplace'
    | '/_app/orders'
    | '/_app/protocol'
    | '/_app/services'
    | '/_app/vault'
    | '/_app/'
    | '/_app/_maps/onboarding'
    | '/_app/_maps/schedule'
    | '/_app/_maps/settings'
    | '/_app/_maps/users'
    | '/_app/concierge/$id'
    | '/_app/data/records'
    | '/_app/family-risk/plan'
    | '/_app/orders/$id'
    | '/_app/plans/$id'
    | '/_app/prescriptions/$id'
    | '/_app/protocol/autopilot'
    | '/_app/protocol/plans'
    | '/_app/protocol/reveal'
    | '/_app/questionnaire/$type'
    | '/_app/services/$id'
    | '/setpassword/$id/$secret'
    | '/_app/concierge/'
    | '/_app/data/'
    | '/_app/orders/'
    | '/_app/protocol/'
    | '/_app/services/'
    | '/_app/protocol/plans/$id'
    | '/_app/protocol/reveal/$step'
    | '/_app/protocol/reveal/'
    | '/_app/protocol/plans/$planId/goals/$goalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CheckEmailRoute: typeof CheckEmailRoute
  ClaimBenefitRoute: typeof ClaimBenefitRoute
  LogoutRoute: typeof LogoutRoute
  RegisterRoute: typeof RegisterRoute
  ResetpasswordRoute: typeof ResetpasswordRoute
  SigninRoute: typeof SigninRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  SetpasswordIdSecretRoute: typeof SetpasswordIdSecretRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resetpassword': {
      id: '/resetpassword'
      path: '/resetpassword'
      fullPath: '/resetpassword'
      preLoaderRoute: typeof ResetpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-benefit': {
      id: '/claim-benefit'
      path: '/claim-benefit'
      fullPath: '/claim-benefit'
      preLoaderRoute: typeof ClaimBenefitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vault': {
      id: '/_app/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/protocol': {
      id: '/_app/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof AppProtocolRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invite': {
      id: '/_app/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AppInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intake': {
      id: '/_app/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AppIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/family-risk': {
      id: '/_app/family-risk'
      path: '/family-risk'
      fullPath: '/family-risk'
      preLoaderRoute: typeof AppFamilyRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data': {
      id: '/_app/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/concierge': {
      id: '/_app/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof AppConciergeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_maps': {
      id: '/_app/_maps'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppMapsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppServicesRoute
    }
    '/_app/protocol/': {
      id: '/_app/protocol/'
      path: '/'
      fullPath: '/protocol/'
      preLoaderRoute: typeof AppProtocolIndexRouteImport
      parentRoute: typeof AppProtocolRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/_app/data/': {
      id: '/_app/data/'
      path: '/'
      fullPath: '/data/'
      preLoaderRoute: typeof AppDataIndexRouteImport
      parentRoute: typeof AppDataRoute
    }
    '/_app/concierge/': {
      id: '/_app/concierge/'
      path: '/'
      fullPath: '/concierge/'
      preLoaderRoute: typeof AppConciergeIndexRouteImport
      parentRoute: typeof AppConciergeRoute
    }
    '/setpassword/$id/$secret': {
      id: '/setpassword/$id/$secret'
      path: '/setpassword/$id/$secret'
      fullPath: '/setpassword/$id/$secret'
      preLoaderRoute: typeof SetpasswordIdSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/services/$id': {
      id: '/_app/services/$id'
      path: '/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof AppServicesIdRouteImport
      parentRoute: typeof AppServicesRoute
    }
    '/_app/questionnaire/$type': {
      id: '/_app/questionnaire/$type'
      path: '/questionnaire/$type'
      fullPath: '/questionnaire/$type'
      preLoaderRoute: typeof AppQuestionnaireTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/protocol/reveal': {
      id: '/_app/protocol/reveal'
      path: '/reveal'
      fullPath: '/protocol/reveal'
      preLoaderRoute: typeof AppProtocolRevealRouteImport
      parentRoute: typeof AppProtocolRoute
    }
    '/_app/protocol/plans': {
      id: '/_app/protocol/plans'
      path: '/plans'
      fullPath: '/protocol/plans'
      preLoaderRoute: typeof AppProtocolPlansRouteImport
      parentRoute: typeof AppProtocolRoute
    }
    '/_app/protocol/autopilot': {
      id: '/_app/protocol/autopilot'
      path: '/autopilot'
      fullPath: '/protocol/autopilot'
      preLoaderRoute: typeof AppProtocolAutopilotRouteImport
      parentRoute: typeof AppProtocolRoute
    }
    '/_app/prescriptions/$id': {
      id: '/_app/prescriptions/$id'
      path: '/prescriptions/$id'
      fullPath: '/prescriptions/$id'
      preLoaderRoute: typeof AppPrescriptionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans/$id': {
      id: '/_app/plans/$id'
      path: '/plans/$id'
      fullPath: '/plans/$id'
      preLoaderRoute: typeof AppPlansIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/_app/family-risk/plan': {
      id: '/_app/family-risk/plan'
      path: '/plan'
      fullPath: '/family-risk/plan'
      preLoaderRoute: typeof AppFamilyRiskPlanRouteImport
      parentRoute: typeof AppFamilyRiskRoute
    }
    '/_app/data/records': {
      id: '/_app/data/records'
      path: '/records'
      fullPath: '/data/records'
      preLoaderRoute: typeof AppDataRecordsRouteImport
      parentRoute: typeof AppDataRoute
    }
    '/_app/concierge/$id': {
      id: '/_app/concierge/$id'
      path: '/$id'
      fullPath: '/concierge/$id'
      preLoaderRoute: typeof AppConciergeIdRouteImport
      parentRoute: typeof AppConciergeRoute
    }
    '/_app/_maps/users': {
      id: '/_app/_maps/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppMapsUsersRouteImport
      parentRoute: typeof AppMapsRoute
    }
    '/_app/_maps/settings': {
      id: '/_app/_maps/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppMapsSettingsRouteImport
      parentRoute: typeof AppMapsRoute
    }
    '/_app/_maps/schedule': {
      id: '/_app/_maps/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppMapsScheduleRouteImport
      parentRoute: typeof AppMapsRoute
    }
    '/_app/_maps/onboarding': {
      id: '/_app/_maps/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppMapsOnboardingRouteImport
      parentRoute: typeof AppMapsRoute
    }
    '/_app/protocol/reveal/': {
      id: '/_app/protocol/reveal/'
      path: '/'
      fullPath: '/protocol/reveal/'
      preLoaderRoute: typeof AppProtocolRevealIndexRouteImport
      parentRoute: typeof AppProtocolRevealRoute
    }
    '/_app/protocol/reveal/$step': {
      id: '/_app/protocol/reveal/$step'
      path: '/$step'
      fullPath: '/protocol/reveal/$step'
      preLoaderRoute: typeof AppProtocolRevealStepRouteImport
      parentRoute: typeof AppProtocolRevealRoute
    }
    '/_app/protocol/plans/$id': {
      id: '/_app/protocol/plans/$id'
      path: '/$id'
      fullPath: '/protocol/plans/$id'
      preLoaderRoute: typeof AppProtocolPlansIdRouteImport
      parentRoute: typeof AppProtocolPlansRoute
    }
    '/_app/protocol/plans/$planId/goals/$goalId': {
      id: '/_app/protocol/plans/$planId/goals/$goalId'
      path: '/$planId/goals/$goalId'
      fullPath: '/protocol/plans/$planId/goals/$goalId'
      preLoaderRoute: typeof AppProtocolPlansPlanIdGoalsGoalIdRouteImport
      parentRoute: typeof AppProtocolPlansRoute
    }
  }
}

interface AppMapsRouteChildren {
  AppMapsOnboardingRoute: typeof AppMapsOnboardingRoute
  AppMapsScheduleRoute: typeof AppMapsScheduleRoute
  AppMapsSettingsRoute: typeof AppMapsSettingsRoute
  AppMapsUsersRoute: typeof AppMapsUsersRoute
}

const AppMapsRouteChildren: AppMapsRouteChildren = {
  AppMapsOnboardingRoute: AppMapsOnboardingRoute,
  AppMapsScheduleRoute: AppMapsScheduleRoute,
  AppMapsSettingsRoute: AppMapsSettingsRoute,
  AppMapsUsersRoute: AppMapsUsersRoute,
}

const AppMapsRouteWithChildren =
  AppMapsRoute._addFileChildren(AppMapsRouteChildren)

interface AppConciergeRouteChildren {
  AppConciergeIdRoute: typeof AppConciergeIdRoute
  AppConciergeIndexRoute: typeof AppConciergeIndexRoute
}

const AppConciergeRouteChildren: AppConciergeRouteChildren = {
  AppConciergeIdRoute: AppConciergeIdRoute,
  AppConciergeIndexRoute: AppConciergeIndexRoute,
}

const AppConciergeRouteWithChildren = AppConciergeRoute._addFileChildren(
  AppConciergeRouteChildren,
)

interface AppDataRouteChildren {
  AppDataRecordsRoute: typeof AppDataRecordsRoute
  AppDataIndexRoute: typeof AppDataIndexRoute
}

const AppDataRouteChildren: AppDataRouteChildren = {
  AppDataRecordsRoute: AppDataRecordsRoute,
  AppDataIndexRoute: AppDataIndexRoute,
}

const AppDataRouteWithChildren =
  AppDataRoute._addFileChildren(AppDataRouteChildren)

interface AppFamilyRiskRouteChildren {
  AppFamilyRiskPlanRoute: typeof AppFamilyRiskPlanRoute
}

const AppFamilyRiskRouteChildren: AppFamilyRiskRouteChildren = {
  AppFamilyRiskPlanRoute: AppFamilyRiskPlanRoute,
}

const AppFamilyRiskRouteWithChildren = AppFamilyRiskRoute._addFileChildren(
  AppFamilyRiskRouteChildren,
)

interface AppOrdersRouteChildren {
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
}

const AppOrdersRouteChildren: AppOrdersRouteChildren = {
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
}

const AppOrdersRouteWithChildren = AppOrdersRoute._addFileChildren(
  AppOrdersRouteChildren,
)

interface AppProtocolPlansRouteChildren {
  AppProtocolPlansIdRoute: typeof AppProtocolPlansIdRoute
  AppProtocolPlansPlanIdGoalsGoalIdRoute: typeof AppProtocolPlansPlanIdGoalsGoalIdRoute
}

const AppProtocolPlansRouteChildren: AppProtocolPlansRouteChildren = {
  AppProtocolPlansIdRoute: AppProtocolPlansIdRoute,
  AppProtocolPlansPlanIdGoalsGoalIdRoute:
    AppProtocolPlansPlanIdGoalsGoalIdRoute,
}

const AppProtocolPlansRouteWithChildren =
  AppProtocolPlansRoute._addFileChildren(AppProtocolPlansRouteChildren)

interface AppProtocolRevealRouteChildren {
  AppProtocolRevealStepRoute: typeof AppProtocolRevealStepRoute
  AppProtocolRevealIndexRoute: typeof AppProtocolRevealIndexRoute
}

const AppProtocolRevealRouteChildren: AppProtocolRevealRouteChildren = {
  AppProtocolRevealStepRoute: AppProtocolRevealStepRoute,
  AppProtocolRevealIndexRoute: AppProtocolRevealIndexRoute,
}

const AppProtocolRevealRouteWithChildren =
  AppProtocolRevealRoute._addFileChildren(AppProtocolRevealRouteChildren)

interface AppProtocolRouteChildren {
  AppProtocolAutopilotRoute: typeof AppProtocolAutopilotRoute
  AppProtocolPlansRoute: typeof AppProtocolPlansRouteWithChildren
  AppProtocolRevealRoute: typeof AppProtocolRevealRouteWithChildren
  AppProtocolIndexRoute: typeof AppProtocolIndexRoute
}

const AppProtocolRouteChildren: AppProtocolRouteChildren = {
  AppProtocolAutopilotRoute: AppProtocolAutopilotRoute,
  AppProtocolPlansRoute: AppProtocolPlansRouteWithChildren,
  AppProtocolRevealRoute: AppProtocolRevealRouteWithChildren,
  AppProtocolIndexRoute: AppProtocolIndexRoute,
}

const AppProtocolRouteWithChildren = AppProtocolRoute._addFileChildren(
  AppProtocolRouteChildren,
)

interface AppServicesRouteChildren {
  AppServicesIdRoute: typeof AppServicesIdRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
}

const AppServicesRouteChildren: AppServicesRouteChildren = {
  AppServicesIdRoute: AppServicesIdRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
}

const AppServicesRouteWithChildren = AppServicesRoute._addFileChildren(
  AppServicesRouteChildren,
)

interface AppRouteChildren {
  AppMapsRoute: typeof AppMapsRouteWithChildren
  AppConciergeRoute: typeof AppConciergeRouteWithChildren
  AppDataRoute: typeof AppDataRouteWithChildren
  AppFamilyRiskRoute: typeof AppFamilyRiskRouteWithChildren
  AppIntakeRoute: typeof AppIntakeRoute
  AppInviteRoute: typeof AppInviteRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppOrdersRoute: typeof AppOrdersRouteWithChildren
  AppProtocolRoute: typeof AppProtocolRouteWithChildren
  AppServicesRoute: typeof AppServicesRouteWithChildren
  AppVaultRoute: typeof AppVaultRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPlansIdRoute: typeof AppPlansIdRoute
  AppPrescriptionsIdRoute: typeof AppPrescriptionsIdRoute
  AppQuestionnaireTypeRoute: typeof AppQuestionnaireTypeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMapsRoute: AppMapsRouteWithChildren,
  AppConciergeRoute: AppConciergeRouteWithChildren,
  AppDataRoute: AppDataRouteWithChildren,
  AppFamilyRiskRoute: AppFamilyRiskRouteWithChildren,
  AppIntakeRoute: AppIntakeRoute,
  AppInviteRoute: AppInviteRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppOrdersRoute: AppOrdersRouteWithChildren,
  AppProtocolRoute: AppProtocolRouteWithChildren,
  AppServicesRoute: AppServicesRouteWithChildren,
  AppVaultRoute: AppVaultRoute,
  AppIndexRoute: AppIndexRoute,
  AppPlansIdRoute: AppPlansIdRoute,
  AppPrescriptionsIdRoute: AppPrescriptionsIdRoute,
  AppQuestionnaireTypeRoute: AppQuestionnaireTypeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CheckEmailRoute: CheckEmailRoute,
  ClaimBenefitRoute: ClaimBenefitRoute,
  LogoutRoute: LogoutRoute,
  RegisterRoute: RegisterRoute,
  ResetpasswordRoute: ResetpasswordRoute,
  SigninRoute: SigninRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  SetpasswordIdSecretRoute: SetpasswordIdSecretRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
