name: PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  test:
    runs-on: arm-2cpu-8gbmem-75gbssd
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Run build, unit & e2e tests, lint, type checks
        run: make test
        env:
          CENTRAL_LICENSE_KEY: ${{ secrets.CENTRAL_LICENSE_KEY }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            mocked-db.json
          retention-days: 30
